before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
