version: 2.1
executors:
  golang:
    docker:
      - image: circleci/golang:1.12

jobs:
  build_and_test:
    executor: golang
    steps:
      - checkout
      - run: go mod download
      - run: go test ./...

  release:
    executor: golang
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  build_and_test:
    jobs:
      - test

  release:
    jobs:
      - build_and_test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
